### PR TITLE
Add id and filename tokens to use in openframe-processing extension

### PR DESCRIPTION
**Pull request by karlosgliberal**
Hello, first thank you very much for this fantastic project.
The request pull it to see if it seems right to add two new tokens:

```javascript
   tokens [ $id] = new_artwork.id;
   tokens [ $filename] = file_name;
```

I'm working on the extension [openFrame-processing](https://www.npmjs.com/package/openframe-processing) and processing-java client needs a directory to run the command. With these two tokens I can create files and directory / tmp easily.

I said thank you very much for the work

### CODE REVIEW

**Comment by jmwohl** [comment]
Hi @karlosgliberal — thanks very much for working on this, will be very exciting to have processing sketches working with Openframe!

I took a look at the extension you're working on, and have a few thoughts:

1) You're using the processing-java cli tool to compile and run a sketch. I'm not sure how performant compiling processing sketches is on the Pi — I think it might be better to expect an "artwork" to be already compiled and ready to run, then just execute the compiled application on the Pi when it is pushed to the frame.

2) If there is some compelling reason to have the sketches compiled on-demand on the Pi, I don't think we'll need to add the extra tokens. Something like this for the `start_command` should work:

`'start_command': '/usr/local/bin/processing-java --sketch=$filepath --output=/tmp/sketch  --force --present'`

Let me know what you think. I'll try to find time to test this out as well... really looking forward to seeing this working!

**Comment by karlosgliberal** [comment]
Thanks for your answer

I tried it with small sketches on the RPI 3 and compiled. Everything depends on the project. The idea of not upload the compilation is to simplify, upload the source file and ready.

But I will yield more testing and see if it is feasible to raise the pde file.


Responding to point two, processing-java requires the pde this file in a directory with the same name as the file. I have done several tests looking for other solutions and not need tokens, but for now do not see them.

I'm still working thanks for everyth

**Comment by jmwohl** [comment]
Ah, I see — if processing-java needs the dir name to be the same as filename, that's an issue since we're renaming the file. Your solution with adding tokens is probably fine, though I may just decide to include the entire artwork object as an argument to the `start_command` function... in any case, I'd like to test it before merging — will try to find time this week.

On the first point, my reasoning for preferring a compiled sketch as the 'artwork' rather than the sketch source code is that it makes the plugin simpler and more universal. For artwork types that get compiled into an executable (e.g. processing, openFrameworks, etc.), any add-ons or third-party libs that the artwork requires get included in the executable. But if you're compiling on-demand on the Pi, then you'd need to figure out a way to include any dependencies as well, which complicates things significantly.

**Comment by karlosgliberal** [comment]
It seems correct approach to directly send the executable, dependency risk may be high.

I will review how you can directly send the executable and I have to do to work in the RPI.

I like the idea of uploading a file as you do in openFrame-glslviewer, but processing-java in part performance can be complicated. I will also study the issue.

Thanks for your time

**Comment by jmwohl** [comment]
@karlosgliberal Hey, not sure if you've worked any more on this, but I'm currently working on another extension that might benefit from having access to these tokens in the `start_command`. I'm going to merge this PR — but please keep in mind our prior discussion!

**Pull request merged**
